pull_request_rules:
  - name: Auto-merge when labeled and dependencies resolved
    conditions:
      - label = mergeit
      - "#depends-on = 0"
    actions:
      merge:
        method: merge
queue_rules:
  - name: Test
    autoqueue: true
merge_protections:
  - name: mergeit
    if: []
    success_conditions:
      - label = mergeit
